name: OIDC Push Test

on:
  workflow_dispatch:  # Kjøres manuelt fra GitHub Actions

jobs:
  push-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Nødvendig for push
      id-token: write  # Nødvendig for OIDC

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Lag testfil
        run: echo "Bridge OIDC test $(date)" > oidc_bridge_test.txt

      - name: Commit og push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add oidc_bridge_test.txt
          git commit -m "OIDC push testfil via GitHub Actions"
          git push
